### ISSUE TITLE
slice out of bounds

### ISSUE THREAD

**Issue by boyter** [boyter/cs#11]
```

 
 {"level":"info","unique_code":"e237c070","time":"2020-04-27T04:15:56+02:00","message":"level 1 cache hit"}
 ERROR   2020/04/27 04:15:56 server.go:3059: http: panic serving 127.0.0.1:54022: runtime error: slice bounds out of range [:39] with c
 apacity 32
 goroutine 1746 [running]:
 net/http.(*conn).serve.func1(0xc0006d2280)
         /usr/local/go/src/net/http/server.go:1772 +0x139
 panic(0xaeb3a0, 0xce394fce20)
         /usr/local/go/src/runtime/panic.go:973 +0x396
 github.com/boyter/go-searchcode/vendor/github.com/boyter/cs/string.IndexAllIgnoreCaseUnicode(0xce0fe70e11, 0x6e, 0xc000124090, 0x27, 0
 xffffffffffffffff, 0x0, 0x0, 0x0)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/vendor/github.com/boyter/cs/string/index.go:188 +0xc34
 github.com/boyter/go-searchcode/service.(*Service).findMatchingLines(0xc000116018, 0x2d586d8, 0xc000124090, 0x27, 0xce0fe70000, 0x322c
 , 0xcd98f1c400, 0x9, 0x10)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/service/search.go:485 +0x16cb
 github.com/boyter/go-searchcode/service.(*Service).Search(0xc000116018, 0xc000124090, 0x27, 0xc000693700, 0xb, 0xd, 0x14, 0x117d738, 0
 x0, 0x0, ...)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/service/search.go:244 +0xd76
 github.com/boyter/go-searchcode/handlers.(*Application).search(0xc000116000, 0xcb8240, 0xcdfd6ba0e0, 0xc00062a200, 0xc000124090, 0x27,
  0x171b96b689c)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/handlers/handler.go:172 +0x483
 github.com/boyter/go-searchcode/handlers.(*Application).Home(0xc000116000, 0xcb8240, 0xcdfd6ba0e0, 0xc00062a200)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/handlers/handler.go:104 +0x377
 net/http.HandlerFunc.ServeHTTP(0xc000684fc0, 0xcb8240, 0xcdfd6ba0e0, 0xc00062a200)
         /usr/local/go/src/net/http/server.go:2012 +0x44
 github.com/boyter/go-searchcode/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001840c0, 0xcb8240, 0xcdfd6ba0e0, 0xc000255400)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/vendor/github.com/gorilla/mux/mux.go:210 +0xe2
 net/http.serverHandler.ServeHTTP(0xcdfad0c000, 0xcb8240, 0xcdfd6ba0e0, 0xc000255400)
         /usr/local/go/src/net/http/server.go:2807 +0xa3
 net/http.(*conn).serve(0xc0006d2280, 0xcb9480, 0xc00021e440)
         /usr/local/go/src/net/http/server.go:1895 +0x86c
 created by net/http.(*Server).Serve
         /usr/local/go/src/net/http/server.go:2933 +0x35c
 
 
 ERROR   2020/04/28 01:03:25 server.go:3059: http: panic serving 127.0.0.1:33876: runtime error: slice bounds out of range [:53] with c
 apacity 48
 goroutine 2871 [running]:
 net/http.(*conn).serve.func1(0xc02cdd86e0)
         /usr/local/go/src/net/http/server.go:1772 +0x139
 panic(0xaec140, 0xc032069f80)
         /usr/local/go/src/runtime/panic.go:973 +0x396
 github.com/boyter/go-searchcode/vendor/github.com/boyter/cs/string.IndexAllIgnoreCaseUnicode(0xc032de6902, 0x62, 0xc028ba4d80, 0x35, 0
 xffffffffffffffff, 0x0, 0x0, 0x0)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/vendor/github.com/boyter/cs/string/index.go:188 +0xc34
 github.com/boyter/go-searchcode/service.(*Service).findMatchingLines(0xc0002cc018, 0x7a9a66b, 0xc028ba4d80, 0x35, 0xc030680000, 0x3151
 4, 0xc032701000, 0xf, 0x10)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/service/search.go:485 +0x16cb
 github.com/boyter/go-searchcode/service.(*Service).Search(0xc0002cc018, 0xc028ba4d80, 0x35, 0xc028de6420, 0x15, 0x0, 0x14, 0x117e738,
 0x0, 0x0, ...)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/service/search.go:244 +0xd76
 github.com/boyter/go-searchcode/handlers.(*Application).search(0xc0002cc000, 0xcb95c0, 0xc028df2000, 0xc028df4000, 0xc028ba4d80, 0x35,
  0x171bde18370)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/handlers/handler.go:172 +0x483
 github.com/boyter/go-searchcode/handlers.(*Application).Home(0xc0002cc000, 0xcb95c0, 0xc028df2000, 0xc028df4000)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/handlers/handler.go:104 +0x377
 net/http.HandlerFunc.ServeHTTP(...)
         /usr/local/go/src/net/http/server.go:2012
 github.com/boyter/go-searchcode/handlers.IpRestrictorHandler.func1(0xcb95c0, 0xc028df2000, 0xc028df4000)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/handlers/wrapper.go:59 +0x177
 net/http.HandlerFunc.ServeHTTP(0xc00069a9a0, 0xcb95c0, 0xc028df2000, 0xc028df4000)
         /usr/local/go/src/net/http/server.go:2012 +0x44
 github.com/boyter/go-searchcode/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001640c0, 0xcb95c0, 0xc028df2000, 0xc028191e00)
         /home/bboyter/Go/src/github.com/boyter/go-searchcode/vendor/github.com/gorilla/mux/mux.go:210 +0xe2
 net/http.serverHandler.ServeHTTP(0xc0135de000, 0xcb95c0, 0xc028df2000, 0xc028191e00)
         /usr/local/go/src/net/http/server.go:2807 +0xa3
 net/http.(*conn).serve(0xc02cdd86e0, 0xcba800, 0xc02818db00)
         /usr/local/go/src/net/http/server.go:1895 +0x86c
 created by net/http.(*Server).Serve
         /usr/local/go/src/net/http/server.go:2933 +0x35c
```

No idea what is causing this, but probably need to fuzz the input to see if this can be itentiified.

**Comment by boyter** [comment]
Ran massive fuzz tester to try and nail this down

```
020/05/20 14:23:13 workers: 12, corpus: 1473 (52m38s ago), crashers: 0, restarts: 1/9996, execs: 171550918 (54048/sec), cover: 299, uptime: 52m54s
```

Looks like it is resolved. Change was to add at the start of the method and all crashes went away.

```
// The below needed to avoid timeout crash found using go-fuzz
if len(haystack) == 0 || len(needle) == 0 {
	return nil
}
```
